/**
 * Shared copyright and confidentiality constants for PDF reports.
 *
 * These live in lib/pdf/ (not in app/ or components/) because they are
 * PDF-only — they must NOT appear in the web report view.
 */

export function getCopyrightLine(): string {
  return `© ${new Date().getFullYear()} Modern Signal Advisory. All rights reserved.`;
}

export const COPYRIGHT_LINE = getCopyrightLine();

export const CONFIDENTIALITY_NOTICE =
  "Confidential. This intelligence brief is prepared exclusively for the use of the commissioning advisor and their designated clients. Redistribution without written consent of Modern Signal Advisory is prohibited.";

export const DATA_SOURCES_NOTICE =
  "Report generated by Modern Signal Advisory intelligence platform. Data sources include public records, MLS feeds, and third-party analytics. This report does not constitute legal, financial, or appraisal advice.";
