import "@testing-library/jest-dom";
import { render, screen, fireEvent, waitFor, act } from "@testing-library/react";
import React from "react";
import fs from "fs";
import path from "path";

jest.mock("framer-motion", () => {
  const React = require("react");
  return {
    motion: {
      div: React.forwardRef(({ initial, animate, exit, variants, whileTap, ...props }: Record<string, unknown>, ref: React.Ref<HTMLDivElement>) => React.createElement("div", { ...props, ref })),
      button: React.forwardRef(({ initial, animate, exit, variants, whileTap, ...props }: Record<string, unknown>, ref: React.Ref<HTMLButtonElement>) => React.createElement("button", { ...props, ref })),
    },
    AnimatePresence: ({ children }: { children: React.ReactNode }) => React.createElement(React.Fragment, null, children),
  };
});

const MOCK_PERSONAS = [
  { id: "p1", slug: "the-business-mogul", name: "The Business Mogul", tagline: "Real estate as a strategic asset class", primaryMotivation: "Status + Asset Strategy", profileOverview: "Analytical, data-driven buyers who view luxury real estate as a portfolio play.", whatWinsThem: "Data, market intelligence, exclusivity", biggestFear: "Overpaying or missing market data", narrativeFraming: { keyVocabulary: ["ROI", "leverage", "allocation"] }, reportMetrics: ["Cash transaction ratio", "Price-per-sqft trend", "Inventory absorption rate"], talkingPointTemplates: ["Based on the data, this market shows..."], displayOrder: 1 },
  { id: "p2", slug: "the-legacy-builder", name: "The Legacy Builder", tagline: "Creating a lasting family legacy", primaryMotivation: "Meaning + Legacy", profileOverview: "Family-oriented buyers focused on intergenerational wealth.", whatWinsThem: "Story + emotional significance", biggestFear: "Losing family connection", narrativeFraming: { keyVocabulary: ["legacy", "heritage", "family"] }, reportMetrics: ["Historical appreciation", "Neighborhood stability", "School quality"], talkingPointTemplates: ["This property tells a story of..."], displayOrder: 2 },
  { id: "p3", slug: "the-coastal-escape-seeker", name: "The Coastal Escape Seeker", tagline: "The ultimate waterfront retreat", primaryMotivation: "Lifestyle + Relaxation", profileOverview: "Lifestyle buyers seeking waterfront serenity.", whatWinsThem: "Views, access, lifestyle amenities", biggestFear: "Insurance and weather risk", narrativeFraming: { keyVocabulary: ["retreat", "waterfront", "lifestyle"] }, reportMetrics: ["Waterfront premium", "Days on market", "Seasonal demand"], talkingPointTemplates: ["The waterfront lifestyle here offers..."], displayOrder: 3 },
  { id: "p4", slug: "the-tech-founder", name: "The Tech Founder", tagline: "Smart homes for smart money", primaryMotivation: "Innovation + Privacy", profileOverview: "Tech-savvy buyers who want cutting-edge properties.", whatWinsThem: "Smart home tech, privacy, modern design", biggestFear: "Outdated infrastructure", narrativeFraming: { keyVocabulary: ["smart", "connected", "modern"] }, reportMetrics: ["New construction ratio", "Tech infrastructure score", "Privacy index"], talkingPointTemplates: ["This market's tech infrastructure supports..."], displayOrder: 4 },
  { id: "p5", slug: "the-seasonal-second-home-buyer", name: "The Seasonal & Second-Home Buyer", tagline: "The perfect escape, on their schedule", primaryMotivation: "Flexibility + Rental Income", profileOverview: "Buyers seeking seasonal properties with income potential.", whatWinsThem: "Rental yield, seasonal demand, management ease", biggestFear: "Vacancy and maintenance burden", narrativeFraming: { keyVocabulary: ["seasonal", "rental", "flexible"] }, reportMetrics: ["Rental yield", "Occupancy rate", "Seasonal price delta"], talkingPointTemplates: ["The seasonal market here shows..."], displayOrder: 5 },
  { id: "p6", slug: "the-international-buyer", name: "The International Buyer", tagline: "Global wealth, local luxury", primaryMotivation: "Diversification + Prestige", profileOverview: "International buyers seeking US luxury real estate.", whatWinsThem: "Currency advantage, legal clarity, prestige address", biggestFear: "Legal complexity and cultural barriers", narrativeFraming: { keyVocabulary: ["global", "diversification", "prestige"] }, reportMetrics: ["International buyer share", "Currency impact", "Visa-linked demand"], talkingPointTemplates: ["For international buyers, this market offers..."], displayOrder: 6 },
  { id: "p7", slug: "the-celebrity-public-figure", name: "The Celebrity / Public Figure", tagline: "Privacy meets prestige", primaryMotivation: "Privacy + Status", profileOverview: "High-profile buyers demanding absolute privacy.", whatWinsThem: "Privacy, security, discretion", biggestFear: "Exposure and paparazzi", narrativeFraming: { keyVocabulary: ["private", "exclusive", "discreet"] }, reportMetrics: ["Gated community ratio", "Privacy score", "Celebrity density"], talkingPointTemplates: ["This area offers the kind of privacy..."], displayOrder: 7 },
  { id: "p8", slug: "the-corporate-executive", name: "The Corporate Executive", tagline: "Executive living, zero compromises", primaryMotivation: "Efficiency + Quality", profileOverview: "C-suite executives who optimize everything, including their home.", whatWinsThem: "Proximity, quality, turnkey readiness", biggestFear: "Time waste and compromised quality", narrativeFraming: { keyVocabulary: ["efficient", "premium", "turnkey"] }, reportMetrics: ["Commute index", "Turnkey ratio", "Quality-per-dollar"], talkingPointTemplates: ["For executives, this market delivers..."], displayOrder: 8 },
];

function mockFetchSuccess(personas = MOCK_PERSONAS) {
  global.fetch = jest.fn((url: string | URL | Request) => {
    const urlStr = typeof url === "string" ? url : url.toString();
    if (urlStr.includes("/api/buyer-personas/")) {
      const slug = urlStr.split("/api/buyer-personas/")[1];
      const persona = personas.find((p) => p.slug === slug);
      return Promise.resolve({ ok: true, json: () => Promise.resolve({ persona }) } as Response);
    }
    if (urlStr.includes("/api/buyer-personas")) {
      return Promise.resolve({ ok: true, json: () => Promise.resolve({ personas }) } as Response);
    }
    return Promise.resolve({ ok: false, json: () => Promise.resolve({ error: "Not found" }) } as Response);
  }) as jest.Mock;
}

function mockFetchEmpty() {
  global.fetch = jest.fn(() => Promise.resolve({ ok: true, json: () => Promise.resolve({ personas: [] }) } as Response)) as jest.Mock;
}

function mockFetchError() {
  global.fetch = jest.fn(() => Promise.resolve({ ok: false, status: 500, json: () => Promise.resolve({ error: "Internal server error" }) } as Response)) as jest.Mock;
}

describe("Step 4: Your Audience (#155)", () => {
  describe("File structure", () => {
    it("CMP-155-01: has StepYourAudience component", () => {
      expect(fs.existsSync(path.join(process.cwd(), "components/reports/steps/step-your-audience.tsx"))).toBe(true);
    });
  });

  describe("StepYourAudience", () => {
    let StepYourAudience: React.ComponentType<{ onStepComplete: (data: { personaIds: string[] }) => void; onValidationChange?: (valid: boolean) => void }>;

    beforeAll(async () => {
      const mod = await import("@/components/reports/steps/step-your-audience");
      StepYourAudience = mod.StepYourAudience;
    });

    afterEach(() => { jest.restoreAllMocks(); });

    it("CMP-155-02: renders heading", async () => { mockFetchSuccess(); render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); expect(screen.getByText("Who are you advising?")).toBeInTheDocument(); });
    it("CMP-155-03: renders helper text", async () => { mockFetchSuccess(); render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); expect(screen.getByText(/Select up to 3 buyer personas/)).toBeInTheDocument(); });
    it("CMP-155-04: renders accent divider", async () => { mockFetchSuccess(); render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); expect(document.querySelector(".bg-\\[var\\(--color-accent\\)\\]")).toBeInTheDocument(); });

    it("CMP-155-05: renders all 8 personas", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); expect(screen.getByText("The Legacy Builder")).toBeInTheDocument(); expect(screen.getByText("The Coastal Escape Seeker")).toBeInTheDocument(); expect(screen.getByText("The Tech Founder")).toBeInTheDocument(); expect(screen.getByText("The Seasonal & Second-Home Buyer")).toBeInTheDocument(); expect(screen.getByText("The International Buyer")).toBeInTheDocument(); expect(screen.getByText("The Celebrity / Public Figure")).toBeInTheDocument(); expect(screen.getByText("The Corporate Executive")).toBeInTheDocument(); });
    it("CMP-155-06: cards show tagline", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("Real estate as a strategic asset class")).toBeInTheDocument(); }); expect(screen.getByText("Creating a lasting family legacy")).toBeInTheDocument(); });
    it("CMP-155-07: cards show motivation badge", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("Status + Asset Strategy")).toBeInTheDocument(); }); expect(screen.getByText("Meaning + Legacy")).toBeInTheDocument(); });
    it("CMP-155-08: cards show whatWinsThem", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText(/Data, market intelligence, exclusivity/)).toBeInTheDocument(); }); expect(screen.getByText(/Story \+ emotional significance/)).toBeInTheDocument(); });
    it("CMP-155-09: cards have View Profile bar", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getAllByRole("button", { name: /View profile for/ }).length).toBe(8); }); });
    it("CMP-155-10: cards in displayOrder", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const cards = screen.getAllByTestId("audience-persona-card"); const names = cards.map((c) => c.querySelector("[data-testid='persona-name']")?.textContent); expect(names).toEqual(["The Business Mogul", "The Legacy Builder", "The Coastal Escape Seeker", "The Tech Founder", "The Seasonal & Second-Home Buyer", "The International Buyer", "The Celebrity / Public Figure", "The Corporate Executive"]); });

    it("CMP-155-11: clicking selects", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const card = screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!; fireEvent.click(card); expect(card).toHaveAttribute("data-selected", "true"); });
    it("CMP-155-12: shows selection badge", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); fireEvent.click(screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!); expect(screen.getByTestId("selection-badge-1")).toBeInTheDocument(); });
    it("CMP-155-13: clicking deselects", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const card = screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!; fireEvent.click(card); expect(card).toHaveAttribute("data-selected", "true"); fireEvent.click(card); expect(card).toHaveAttribute("data-selected", "false"); });
    it("CMP-155-14: select up to 3", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); expect(screen.getByTestId("selection-badge-1")).toBeInTheDocument(); expect(screen.getByTestId("selection-badge-2")).toBeInTheDocument(); expect(screen.getByTestId("selection-badge-3")).toBeInTheDocument(); });
    it("CMP-155-15: deselect renumbers badges", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); fireEvent.click(g("The Legacy Builder")); expect(screen.getByTestId("selection-badge-1")).toBeInTheDocument(); expect(screen.getByTestId("selection-badge-2")).toBeInTheDocument(); expect(screen.queryByTestId("selection-badge-3")).not.toBeInTheDocument(); });

    it("CMP-155-16: max-3 explanation", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); expect(screen.getByText(/You've chosen 3 personas.*that's the max for a focused report/)).toBeInTheDocument(); });
    it("CMP-155-17: unselected dim at max", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); expect(g("The Coastal Escape Seeker")).toHaveAttribute("aria-disabled", "true"); });
    it("CMP-155-18: dimmed card noop", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); fireEvent.click(g("The Coastal Escape Seeker")); expect(g("The Coastal Escape Seeker")).toHaveAttribute("data-selected", "false"); });
    it("CMP-155-19: max explanation disappears", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); expect(screen.getByText(/You've chosen 3 personas/)).toBeInTheDocument(); fireEvent.click(g("The Tech Founder")); expect(screen.queryByText(/You've chosen 3 personas/)).not.toBeInTheDocument(); });
    it("CMP-155-20: dimmed cards recover", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); expect(g("The Coastal Escape Seeker")).toHaveAttribute("aria-disabled", "true"); fireEvent.click(g("The Tech Founder")); expect(g("The Coastal Escape Seeker")).not.toHaveAttribute("aria-disabled", "true"); });

    it("CMP-155-21: View Profile opens panel", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByTestId("audience-preview-panel")).toBeInTheDocument(); }); });
    it("CMP-155-22: panel shows overview", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByText(/Analytical, data-driven buyers/)).toBeInTheDocument(); }); });
    it("CMP-155-23: panel shows decision signals", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByText(/What Wins Them/)).toBeInTheDocument(); expect(screen.getByText(/Biggest Fear/)).toBeInTheDocument(); }); });
    it("CMP-155-24: panel shows vocabulary tags", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByText("ROI")).toBeInTheDocument(); expect(screen.getByText("leverage")).toBeInTheDocument(); expect(screen.getByText("allocation")).toBeInTheDocument(); }); });
    it("CMP-155-25: panel shows metrics", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByText("Cash transaction ratio")).toBeInTheDocument(); expect(screen.getByText("Price-per-sqft trend")).toBeInTheDocument(); expect(screen.getByText("Inventory absorption rate")).toBeInTheDocument(); }); });
    it("CMP-155-26: panel shows talking point", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByText(/Based on the data, this market shows/)).toBeInTheDocument(); }); });
    it("CMP-155-27: panel has close button", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByRole("button", { name: "Close preview" })).toBeInTheDocument(); }); });
    it("CMP-155-28: close button closes panel", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByTestId("audience-preview-panel")).toBeInTheDocument(); }); fireEvent.click(screen.getByRole("button", { name: "Close preview" })); await waitFor(() => { expect(screen.queryByTestId("audience-preview-panel")).not.toBeInTheDocument(); }); });
    it("CMP-155-29: preview switches", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByText(/Analytical, data-driven buyers/)).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[1]); }); await waitFor(() => { expect(screen.getByText(/Family-oriented buyers/)).toBeInTheDocument(); }); });
    it("CMP-155-30: select keeps panel open", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByTestId("audience-preview-panel")).toBeInTheDocument(); }); fireEvent.click(screen.getAllByTestId("audience-persona-card")[0]); expect(screen.getByTestId("audience-preview-panel")).toBeInTheDocument(); });

    it("CMP-155-31: invalid when none selected", async () => { mockFetchSuccess(); const v = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn(), onValidationChange: v })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); expect(v).toHaveBeenCalledWith(false); });
    it("CMP-155-32: valid when one selected", async () => { mockFetchSuccess(); const v = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn(), onValidationChange: v })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); fireEvent.click(screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!); expect(v).toHaveBeenCalledWith(true); });
    it("CMP-155-33: invalid when last deselected", async () => { mockFetchSuccess(); const v = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn(), onValidationChange: v })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const card = screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!; fireEvent.click(card); fireEvent.click(card); expect(v).toHaveBeenLastCalledWith(false); });

    it("CMP-155-34: emits in selection order", async () => { mockFetchSuccess(); const s = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: s })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Business Mogul")); expect(s.mock.calls[s.mock.calls.length - 1][0].personaIds).toEqual(["p2", "p1"]); });
    it("CMP-155-35: no emit when empty", async () => { mockFetchSuccess(); const s = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: s })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); expect(s.mock.calls.filter((c: [{ personaIds: string[] }]) => c[0].personaIds.length > 0).length).toBe(0); });
    it("CMP-155-36: updates on every change", async () => { mockFetchSuccess(); const s = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: s })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Business Mogul")); expect(s.mock.calls[s.mock.calls.length - 1][0].personaIds).toEqual(["p2"]); });

    it("CMP-155-37: empty personas message", async () => { mockFetchEmpty(); const v = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn(), onValidationChange: v })); }); await waitFor(() => { expect(screen.getByText(/No buyer personas are configured yet/)).toBeInTheDocument(); }); expect(v).toHaveBeenCalledWith(true); });
    it("CMP-155-38: loading skeleton", async () => { global.fetch = jest.fn(() => new Promise(() => {})) as jest.Mock; render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); const skeleton = screen.getByTestId("audience-loading-skeleton"); expect(skeleton).toBeInTheDocument(); expect(skeleton).toHaveAttribute("aria-busy", "true"); });
    it("CMP-155-39: heading during loading", () => { global.fetch = jest.fn(() => new Promise(() => {})) as jest.Mock; render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); expect(screen.getByText("Who are you advising?")).toBeInTheDocument(); expect(screen.getByText(/Select up to 3 buyer personas/)).toBeInTheDocument(); });
    it("CMP-155-40: error message on API fail", async () => { mockFetchError(); const v = jest.fn(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn(), onValidationChange: v })); }); await waitFor(() => { expect(screen.getByText(/We couldn't load buyer personas/)).toBeInTheDocument(); }); expect(v).toHaveBeenCalledWith(true); });
    it("CMP-155-41: Retry re-fetches", async () => { mockFetchError(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("Retry")).toBeInTheDocument(); }); mockFetchSuccess(); await act(async () => { fireEvent.click(screen.getByText("Retry")); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); });

    it("CMP-155-42: cards have role switch", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); expect(screen.getAllByRole("switch").length).toBe(8); });
    it("CMP-155-43: unselected aria-checked false", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); screen.getAllByRole("switch").forEach((s) => { expect(s).toHaveAttribute("aria-checked", "false"); }); });
    it("CMP-155-44: selected aria-checked true", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const card = screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!; fireEvent.click(card); expect(card).toHaveAttribute("aria-checked", "true"); });
    it("CMP-155-45: Enter toggles", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const card = screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!; fireEvent.keyDown(card, { key: "Enter" }); expect(card).toHaveAttribute("aria-checked", "true"); });
    it("CMP-155-46: Space toggles", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const card = screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!; fireEvent.keyDown(card, { key: " " }); expect(card).toHaveAttribute("aria-checked", "true"); });
    it("CMP-155-47: panel role complementary", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); await act(async () => { fireEvent.click(screen.getAllByRole("button", { name: /View profile for/ })[0]); }); await waitFor(() => { expect(screen.getByTestId("audience-preview-panel")).toHaveAttribute("role", "complementary"); }); });
    it("CMP-155-48: badge aria-label", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); fireEvent.click(screen.getByText("The Business Mogul").closest("[data-testid='audience-persona-card']")!); expect(screen.getByTestId("selection-badge-1")).toHaveAttribute("aria-label", "Selected, position 1"); });
    it("CMP-155-49: maxed cards aria-label", async () => { mockFetchSuccess(); await act(async () => { render(React.createElement(StepYourAudience, { onStepComplete: jest.fn() })); }); await waitFor(() => { expect(screen.getByText("The Business Mogul")).toBeInTheDocument(); }); const g = (n: string) => screen.getByText(n).closest("[data-testid='audience-persona-card']")!; fireEvent.click(g("The Business Mogul")); fireEvent.click(g("The Legacy Builder")); fireEvent.click(g("The Tech Founder")); expect(g("The Coastal Escape Seeker")).toHaveAttribute("aria-label", expect.stringContaining("maximum 3 personas selected")); });
  });
});
