import "@testing-library/jest-dom";

// eslint-disable-next-line @typescript-eslint/no-require-imports
const React = require("react");
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { render, screen } = require("@testing-library/react");

const CURRENT_YEAR = new Date().getFullYear();
const COPYRIGHT_TEXT = `© ${CURRENT_YEAR} Modern Signal Advisory. All rights reserved.`;
const CONFIDENTIALITY_TEXT =
  "Confidential. This intelligence brief is prepared exclusively for the use of the commissioning advisor and their designated clients. Redistribution without written consent of Modern Signal Advisory is prohibited.";
const DATA_SOURCES_TEXT =
  "Report generated by Modern Signal Advisory intelligence platform. Data sources include public records, MLS feeds, and third-party analytics. This report does not constitute legal, financial, or appraisal advice.";

describe("PDF Copyright Notices", () => {
  describe("Scenario: Copyright line appears on every page footer", () => {
    it("SectionPage footer includes copyright line", async () => {
      const { SectionPage } = await import(
        "@/lib/pdf/templates/section-page"
      );

      render(
        React.createElement(SectionPage, {
          section: {
            sectionType: "disclaimer_methodology",
            title: "Methodology & Disclaimer",
            content: { narrative: "Standard methodology.", dataSources: [], disclaimer: "" },
          },
          reportTitle: "Naples Intelligence Report",
          companyName: "Compass",
        })
      );

      expect(screen.getByText(COPYRIGHT_TEXT)).toBeInTheDocument();
    });

    it("TableOfContents footer includes copyright line", async () => {
      const { TableOfContents } = await import(
        "@/lib/pdf/templates/table-of-contents"
      );

      render(
        React.createElement(TableOfContents, {
          sections: [
            {
              sectionType: "executive_briefing",
              title: "Executive Briefing",
              content: {},
            },
          ],
        })
      );

      expect(screen.getByText(COPYRIGHT_TEXT)).toBeInTheDocument();
    });

    it("InsightsIndex footer includes copyright line", async () => {
      const { InsightsIndex } = await import(
        "@/lib/pdf/templates/insights-index"
      );

      render(
        React.createElement(InsightsIndex, {
          metadata: {
            marketId: "naples",
            generatedAt: "2026-03-15T00:00:00Z",
            version: "1.0",
            confidenceScore: 0.85,
            dataSources: [],
          },
          sections: [],
        })
      );

      expect(screen.getByText(COPYRIGHT_TEXT)).toBeInTheDocument();
    });

    it("CoverPage includes copyright line", async () => {
      const { CoverPage } = await import(
        "@/lib/pdf/templates/cover-page"
      );

      render(
        React.createElement(CoverPage, {
          title: "Naples Luxury Market Intelligence Report",
          marketName: "Naples, FL",
          agentName: "Jordan Ellis",
          company: "Compass",
          generatedAt: "2026-03-15T00:00:00Z",
        })
      );

      expect(screen.getByText(COPYRIGHT_TEXT)).toBeInTheDocument();
    });

    it("copyright text uses 7pt Inter in tertiary color", async () => {
      const { styles: pdfStyles, COLORS } = await import(
        "@/lib/pdf/styles"
      );

      expect(pdfStyles.copyrightText).toBeDefined();
      expect(pdfStyles.copyrightText.fontFamily).toBe("Inter");
      expect(pdfStyles.copyrightText.fontSize).toBe(7);
      expect(pdfStyles.copyrightText.color).toBe(COLORS.textTertiary);
    });
  });

  describe("Scenario: Copyright line coexists with existing footer elements", () => {
    it("SectionPage footer still shows report title and page number alongside copyright", async () => {
      const { SectionPage } = await import(
        "@/lib/pdf/templates/section-page"
      );

      render(
        React.createElement(SectionPage, {
          section: {
            sectionType: "disclaimer_methodology",
            title: "Methodology & Disclaimer",
            content: { narrative: "Standard methodology.", dataSources: [], disclaimer: "" },
          },
          reportTitle: "Naples Intelligence Report",
          companyName: "Compass",
        })
      );

      // Existing footer text still present
      expect(
        screen.getByText("Naples Intelligence Report — Compass")
      ).toBeInTheDocument();
      // Copyright also present
      expect(screen.getByText(COPYRIGHT_TEXT)).toBeInTheDocument();
    });

    it("copyright footer row has 4pt paddingTop for minimal spacing", async () => {
      const { styles: pdfStyles } = await import("@/lib/pdf/styles");

      expect(pdfStyles.copyrightFooterRow).toBeDefined();
      expect(pdfStyles.copyrightFooterRow.paddingTop).toBe(4);
    });
  });

  describe("Scenario: Confidentiality disclaimer on cover page", () => {
    it("cover page renders confidentiality notice text", async () => {
      const { CoverPage } = await import(
        "@/lib/pdf/templates/cover-page"
      );

      render(
        React.createElement(CoverPage, {
          title: "Naples Luxury Market Intelligence Report",
          marketName: "Naples, FL",
          agentName: "Jordan Ellis",
          company: "Compass",
          generatedAt: "2026-03-15T00:00:00Z",
        })
      );

      expect(screen.getByText(CONFIDENTIALITY_TEXT)).toBeInTheDocument();
    });

    it("cover confidentiality uses inverse color with reduced opacity", async () => {
      const { styles: pdfStyles, COLORS } = await import(
        "@/lib/pdf/styles"
      );

      expect(pdfStyles.coverConfidentiality).toBeDefined();
      expect(pdfStyles.coverConfidentiality.fontFamily).toBe("Inter");
      expect(pdfStyles.coverConfidentiality.fontSize).toBe(7);
      expect(pdfStyles.coverConfidentiality.color).toBe(COLORS.surface); // #F8FAFC — inverse text
      expect(pdfStyles.coverConfidentiality.opacity).toBeLessThan(1);
    });
  });

  describe("Scenario: Confidentiality disclaimer on final page", () => {
    it("last section page renders confidentiality block when isLastSection=true", async () => {
      const { SectionPage } = await import(
        "@/lib/pdf/templates/section-page"
      );

      render(
        React.createElement(SectionPage, {
          section: {
            sectionType: "competitive_landscape",
            title: "Competitive Landscape",
            content: {},
          },
          reportTitle: "Naples Intelligence Report",
          companyName: "Compass",
          isLastSection: true,
        })
      );

      expect(screen.getByText(CONFIDENTIALITY_TEXT)).toBeInTheDocument();
      expect(screen.getByText(DATA_SOURCES_TEXT)).toBeInTheDocument();
    });

    it("non-last section pages do NOT render confidentiality block", async () => {
      const { SectionPage } = await import(
        "@/lib/pdf/templates/section-page"
      );

      render(
        React.createElement(SectionPage, {
          section: {
            sectionType: "disclaimer_methodology",
            title: "Methodology & Disclaimer",
            content: { narrative: "Standard methodology.", dataSources: [], disclaimer: "" },
          },
          reportTitle: "Naples Intelligence Report",
          companyName: "Compass",
          isLastSection: false,
        })
      );

      expect(screen.queryByText(CONFIDENTIALITY_TEXT)).not.toBeInTheDocument();
      expect(screen.queryByText(DATA_SOURCES_TEXT)).not.toBeInTheDocument();
    });

    it("confidentiality block style has border matching design token", async () => {
      const { styles: pdfStyles, COLORS } = await import(
        "@/lib/pdf/styles"
      );

      expect(pdfStyles.confidentialityBlock).toBeDefined();
      expect(pdfStyles.confidentialityBlock.borderWidth).toBe(1);
      expect(pdfStyles.confidentialityBlock.borderColor).toBe(COLORS.border);
    });
  });

  describe("Scenario: Year in copyright updates automatically", () => {
    it("copyright text contains the current year dynamically", async () => {
      const { SectionPage } = await import(
        "@/lib/pdf/templates/section-page"
      );

      render(
        React.createElement(SectionPage, {
          section: {
            sectionType: "disclaimer_methodology",
            title: "Methodology & Disclaimer",
            content: { narrative: "Standard methodology.", dataSources: [], disclaimer: "" },
          },
          reportTitle: "Test Report",
        })
      );

      const year = new Date().getFullYear();
      expect(
        screen.getByText(new RegExp(`© ${year} Modern Signal Advisory`))
      ).toBeInTheDocument();
    });
  });

  describe("Scenario: Copyright does not appear in web report view", () => {
    it("PDF copyright components are only in lib/pdf/, not in app/ or components/", async () => {
      // This is a structural test — the copyright text and confidentiality disclaimer
      // live exclusively in lib/pdf/templates/*, not in any web-facing component.
      // We verify by importing the shared copyright constants from a pdf-only module.
      const { COPYRIGHT_LINE, CONFIDENTIALITY_NOTICE } = await import(
        "@/lib/pdf/copyright"
      );

      expect(COPYRIGHT_LINE).toContain("Modern Signal Advisory");
      expect(CONFIDENTIALITY_NOTICE).toContain("Confidential");
    });
  });

  describe("Scenario: Agent branding does not override copyright", () => {
    it("copyright always says 'Modern Signal Advisory' even with custom brand colors", async () => {
      const { CoverPage } = await import(
        "@/lib/pdf/templates/cover-page"
      );

      render(
        React.createElement(CoverPage, {
          title: "Custom Brand Report",
          marketName: "Miami, FL",
          agentName: "Custom Agent",
          company: "Custom Realty",
          generatedAt: "2026-03-15T00:00:00Z",
          brandColors: { primary: "#FF0000", accent: "#00FF00" },
        })
      );

      // Copyright must reference Modern Signal Advisory, not the agent's company
      expect(
        screen.getByText(new RegExp(`© \\d{4} Modern Signal Advisory`))
      ).toBeInTheDocument();
      expect(screen.getByText(CONFIDENTIALITY_TEXT)).toBeInTheDocument();
    });

    it("ReportDocument passes isLastSection to final section only", async () => {
      const { ReportDocument } = await import("@/lib/pdf/document");

      const reportData = {
        metadata: {
          marketId: "naples",
          generatedAt: "2026-03-15T00:00:00Z",
          version: "1.0",
          confidenceScore: 0.85,
          dataSources: [],
        },
        sections: [
          {
            sectionType: "disclaimer_methodology",
            title: "Methodology & Disclaimer",
            content: { narrative: "Standard methodology.", dataSources: [], disclaimer: "" },
          },
        ],
      };

      const branding = {
        name: "Jordan Ellis",
        company: "Compass",
        brandColors: { primary: "#1A1A2E", accent: "#E94560" },
      };

      // Renders without error — structural check that document assembles correctly
      const element = React.createElement(ReportDocument, {
        reportData,
        branding,
        title: "Test Report",
        marketName: "Naples, FL",
      });

      render(element);

      // The confidentiality + data sources block should appear (on last section)
      expect(screen.getByText(DATA_SOURCES_TEXT)).toBeInTheDocument();
    });
  });
});
